version: "3"
services:
  node:
    build: .
    user: "node"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
